Fix NoMethodError sexp_type caused by ..
.. Subprocessors::Klass#block returning an Array.

.../sexp_processor-4.10.0/lib/sexp_processor.rb:180:
in `rewrite': undefined method `sexp_type' for #<Array...

This fixes the issue Shane ran into in
https://github.com/jaredbeck/minitest_to_rspec/issues/4
but our test suite is not totally passing on
sexp_processor 4.10.0 yet.